dist: trusty
sudo: required
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
  - postgresql
addons:
  postgresql: 9.5
before_install:
  - pip install -r requirements.txt
  - "psql -c 'create database travis-db-test;' -U postgres"
script: python unit_tests/run.py -v
