language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  global:
  - NODE_ENV=test
  - PGPORT=5433
  - PGHOST=localhost
services:
  - postgresql
addons:
  apt:
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
  postgresql: 9.5
before_install:
  - pip install -r requirements.txt
  - "psql -c 'create database travis-db-test;' -U postgres"
  - psql -U postgres travis-db-test -c 'create extension "uuid-ossp";'
script: python unit_tests/run.py -v
